import { StyleSheet } from "react-native";

export default StyleSheet.create({
  body: {
    flex: 1,
  },
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#000000",
    justifyContent: "flex-start",
  },
  inner: {
    flexDirection: "row",
    flex: 1,
  },
  video: {
    width: "80%",
    padding: 10,
  },
  videoContent: {
    height: "82.5%",
    position: "relative",
  },
  videoInfo: {
    backgroundColor: "#000",
    height: "17.5%",
    flexDirection: "row",
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    position: "relative",
  },
  playerVideo: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    opacity: 1,
    overlayColor: "#000",
    borderRadius: 10,
  },
  newsBanner: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    opacity: 0.8,
  },
  poster: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    opacity: 1,
  },
  playert: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  weater: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    gap: 20,
    padding: 20,
  },
  weatherImg: {
    width: 40,
    height: 40,
    marginRight: 0,
  },
  cambioImg: {
    width: 35,
    height: 35,
    marginRight: 5,
  },
  weatherCity: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "500",
    maxWidth: "100%",
  },
  weatherDate: {
    color: "#ffffff",
    fontSize: 16,
  },
  weatherTemp: {
    color: "#ffffff",
    fontSize: 30,
    position: "relative",
    fontWeight: "500",
    zIndex: 1,
  },
  infoCity: {
    flexDirection: "column",
  },
  infoTemp: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  boxTemp: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  sourceUrl: {
    position: "absolute",
    bottom: 2,
    right: 2,
    color: "red",
    zIndex: 999999,
    fontSize: 10,
  },
  grau: {
    fontSize: 14,
    textAlignVertical: "top",
    position: "absolute",
    top: 0,
    fontWeight: "500",
  },
  logo: {
    position: "absolute",
    top: 10,
    right: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.8,
    shadowRadius: 11.14,
    elevation: 17,
    zIndex: 999,
  },
  logoImg: {
    width: 70,
    height: 46,
    resizeMode: "cover",
  },
  senhaArea: {
    backgroundColor: "#000",
    width: "20%",
    padding: 10,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  senhaText: {
    color: "#FFF",
    fontSize: 50,
    fontWeight: "bold",
    textAlign: "center",
  },

  senha: {
    width: "100%",
    height: "17.5%",
    marginBottom: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  senhaTitle: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
    textAlign: "center",
    width: "100%",
    padding: 10,
    borderRadius: 5,
    position: "absolute",
    top: 10,
    zIndex: 999999,
  },
  input: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    opacity: 0,
    position: "absolute",
  },

  background: {
    position: "absolute",
    height: "17%", // Altura do background
    bottom: 0,
    width: "100%",
    backgroundColor: "#000", // Cor do background
    opacity: 0.1,
    zIndex: 999999,
    // Opacidade do background (entre 0 e 1)
  },
  newsArea: {
    width: "100%",
    position: "absolute",
    bottom: 0,
    zIndex: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 5.46,
    elevation: 9,
  },
  newsTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "500",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  newsTitleBox: {
    backgroundColor: "red",
    width: "100%",
    opacity: 0.8,
  },
  newsDescription: {
    color: "#ffffff",
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: "flex-start",
    maxWidth: "100%",
    maxHeight: "100%",
    marginBottom: 15,
  },
  newsDescriptionBox: {
    backgroundColor: "#000",
    opacity: 0.8,
    width: "100%",
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  newsFont: {
    color: "#ffffff",
    fontSize: 12,
    position: "absolute",
    bottom: 4,
    right: 4,
    zIndex: 1,
    justifyContent: "flex-start",
  },
  sourceIcon: {
    position: "absolute",
    top: 10,
    borderRadius: 50,
    left: 20,
    width: 40,
    height: 40,
    zIndex: 999999,
  },
  overlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,1)",
    zIndex: 9999,
  },
  balcaonew: {
    width: "50%",
    height: "75%",
    top: "5%",
    backgroundColor: "#000",
    position: "absolute",
    zIndex: 9999999999,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  balcaonewtext: {
    color: "#ffffff",
    fontSize: 200,
    fontWeight: "700",
  },
  balcaonewlabel: {
    color: "#ffffff",
    fontSize: 50,
    fontWeight: "700",
  },
  lastSenha: {
    width: "100%",
    height: "17.5%",
    marginBottom: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  lastSenhaText: {
    color: "#FFF",
    fontSize: 50,
    fontWeight: "bold",
    textAlign: "center",
  },
  lastweatherDate: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
});
